seq = "CAGGGTCAAACAGCTTATTGACAAGAGGAGACAGCTCCCGTCTTGCTTCTTGCTAGTTACTTGGTGTCCGGGCGCCCGGGGATATGCTCGTTGTCTGTCGAGGCTGTCGAAATGTCCTTAGCGACAGTGGCATATCCAAACATAGCTTCAATACTATACAAGTTTAGTAGTACCGATATCGCTCTGTGCTGGCCCTCGGCGTGAATCCCGTAGGCTAAGCTTCCTCACCCGCACGTATTCGTATGCGTAGACGCATCCTAAAATGCCCATTACTAATCCTCCAGGAACACCGCGAAGTCCACAGACGTGGAAAAGAGCTCACTCCAACTAGGACATAGCCACTGTCCAATTAGCCCTCAAAGTAAATGCCTCGTTATTCGAGTGTGGTGTGAGACTTTATGACGGCCGACTTTCACGTGCTTAACTGAGAACTATGGGGTAAAAACGGGTTATCGACTTCCAGGGGTCCATTCAGCCTGACCAAAGTAGACTGCGAGCCCGCAAAAATTGCGCATAATATCGATGCGAAAAGTGGGGCCCCGTATGATGACTACTAGACCTAGCTGCAAGACAACATGGAACCCATTGCATCTCCTCGGACTCCTAATCTTGCTCAGGGCCTATTGCGCCGACAACATACAGCACGGATCTATGCTACGCCTGCATCAGATGCTTGTTACACGTTTCGTATCAACATAATGCTACTGTAAGTCTGCTTGTTCCCAATTTTGTCGAACAACCTTGCTGGCACACCTCTACCACACGGTTTCTGCACAAGCTAGGAAAGTCGTGAGATTAGCGATTTAGTGATTCATTTTTTATCATGAGGCCACCCCTTGTAGACAACTGTGTATATCAACTTAGTCGGATTGCTTTTAACGATTGTAGACTGCGTCCCGACCCTT"

c={}

for i in seq:
    if i not in c:
         c[i] = 1
    else:
        c[i] += 1

print(c)

a = {i:seq.count(i) for i in seq}

print(a)

b={}

for i in seq:
    b[i] = b.get(i, 0) + 1

print(b)